export enum ErrorCodes {
    INVALID_ACTION_ERROR = 400,
    CALL_NOT_FOUND_ERR = 401,
    NO_REGISTERED_PHONE_FOUND_ERROR = 402,
    ACTION_FAILED_UNKNOWN = 403,
    FLEX_NOT_LOGGED_IN_ERROR = 404,
    CALL_TO_BRIDGE_NOT_FOUND = 405,
    CANNOT_DECIDE_CHANNEL = 406,
    CANNOT_ANSWER_ANSWERED = 407,
    CALLS_MUST_BE_ANSWERED = 408,
    COULD_NOT_REGISTER_APP = 409,
}